image: Visual Studio 2017
configuration: Release
version: '{build}'

install:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "false")
    {
      $version = & { git describe --tags } 2>&1
      $baseVersion = (& { git describe --tags --abbrev=0 }) 2>&1
      $prereleaseVersion = $version.SubString($baseVersion.Length)
      $adjustedBaseVersion = $baseVersion.Split(".")
      $adjustedBaseVersion[2] = ($adjustedBaseVersion[2] / 1) + 1
      $env:COMMIT_DESCRIPTION = [System.String]::Join(".", $adjustedBaseVersion) + $prereleaseVersion
    }
    else
    {
      $env:COMMIT_DESCRIPTION = $env:APPVEYOR_REPO_TAG_NAME
    }

    Update-AppveyorBuild -Version "$env:COMMIT_DESCRIPTION.$env:APPVEYOR_BUILD_NUMBER"

    Add-AppveyorMessage -Message "Build version is $env:COMMIT_DESCRIPTION"


dotnet_csproj:
  patch: true
  file: 'FriendlySpork\FriendlySpork.csproj'
  version: $(commit_description)


before_build:
- cmd: dotnet restore


build:
  project: FriendlySpork.sln


test_script:
  - cmd: dotnet test FriendlySpork.Tests/FriendlySpork.Tests.csproj


artifacts:
- path: '**/*.nupkg'
  name: Nuget Packages
